# Generated by Django 3.2.8 on 2023-04-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='activities/')),
            ],
            options={
                'verbose_name_plural': 'Club',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('budget', models.FileField(upload_to='budget/')),
                ('event_poster', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('is_approved_by_dean', models.BooleanField(default=False)),
                ('is_approved_by_cfo', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('dean_reject_msg', models.TextField(max_length=800, null=True)),
                ('cfo_reject_msg', models.TextField(max_length=800, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events_add', to='event.Event'),
        ),
        migrations.AddField(
            model_name='club',
            name='factuly_incharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.member'),
        ),
    ]
