# Generated by Django 3.2.8 on 2023-04-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Campus', 'Campus'), ('Hostel', 'Hostel'), ('Academic', 'Academic'), ('Transport', 'Transport'), ('Electrical', 'Electrical')], default='Campus', max_length=50)),
                ('complaint', models.TextField(max_length=800)),
                ('related_document', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('reply', models.TextField(max_length=800, null=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.member')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
