# Generated by Django 3.2.8 on 2023-04-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('grivance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean_message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.member'),
        ),
    ]
