# Generated by Django 3.2.8 on 2023-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grivance', '0003_alter_dean_message_related_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean_message',
            name='related_document',
            field=models.FileField(blank=True, default='not_availabe.jpeg', null=True, upload_to='complaints/'),
        ),
    ]
